export const CHANGE_SUPER_VARIABLE = 'CHANGE_SUPER_VARIABLE';
export const CHANGE_NAME_VARIABLE = 'CHANGE_NAME_VARIABLE';
export const CHANGE_EMAIL_VARIABLE = 'CHANGE_EMAIL_VARIABLE';
export const CHANGE_PASS_VARIABLE = 'CHANGE_PASS_VARIABLE';
export const CHANGE_PASSREPEAT_VARIABLE = 'CHANGE_PASSREPEAT_VARIABLE';
export const CHANGE_PASSERROR_VARIABLE = 'CHANGE_PASSERROR_VARIABLE';
